<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQiMnMpx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQiMnMpx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQiMnMpx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQiMnMpx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQiMnMpx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'QiMnMpx',
    'container.build_id' => 'c71450d9',
    'container.build_time' => 1649842773,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQiMnMpx');
