accueil:
    path: /accueil
    controller: App\Controller\AccueilController::index
connexion:
     path: /connexion
     controller: App\Controller\ConnexionController::index
     
inscription:
     path: /inscription
     controller: App\Controller\InscriptionController::index

contact:
     path: /contact
     controller: App\Controller\ContactController::index

